templates:
  scope-summary:
    source:
      sitePath: "/sites/IMS"
      library: "TBC"
      path: "TBC/Scope Summary.docx"
  design-calculation-register:
    source:
      sitePath: "/sites/IMS"
      library: "TBC"
      path: "TBC/Design Calculation Register.xlsx"
  safety-in-design:
    source:
      sitePath: "/"
      library: "Shared Documents"
      path: "1 IMS/005 Forms/PB-IMS-F-065 Safety in Design.xlsm"
  environmental-checklist:
    source:
      sitePath: "/sites/IMS"
      library: "TBC"
      path: "TBC/Environmental Checklist.xlsx"
  authority-approval-checklist:
    source:
      sitePath: "/sites/IMS"
      library: "TBC"
      path: "TBC/Authority Approval Checklist.xlsx"
